apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yaml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: ingestion
  name: ingestion
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ingestion
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file docker-compose.yaml convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: ingestion
    spec:
      containers:
        - args:
            - /opt/airflow/ingestion_dependency.sh
          command:
            - /bin/bash
          env:
            - name: AIRFLOW_DB
              value: airflow_db
            - name: AIRFLOW__API__AUTH_BACKENDS
              value: airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session
            - name: AIRFLOW__CORE__EXECUTOR
              value: LocalExecutor
            - name: AIRFLOW__OPENMETADATA_AIRFLOW_APIS__DAG_GENERATED_CONFIGS
              value: /opt/airflow/dag_generated_configs
            - name: DB_HOST
              value: mysql
            - name: DB_PASSWORD
              value: airflow_pass
            - name: DB_PORT
              value: "3306"
            - name: DB_PROPERTIES
            - name: DB_SCHEME
              value: mysql+pymysql
            - name: DB_USER
              value: airflow_user
          image: docker.getcollate.io/openmetadata/ingestion:1.5.6
          name: openmetadata-ingestion
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /opt/airflow/dag_generated_configs
              name: ingestion-volume-dag-airflow
            - mountPath: /opt/airflow/dags
              name: ingestion-volume-dags
            - mountPath: /tmp
              name: ingestion-volume-tmp
      restartPolicy: Always
      volumes:
        - name: ingestion-volume-dag-airflow
          persistentVolumeClaim:
            claimName: ingestion-volume-dag-airflow
        - name: ingestion-volume-dags
          persistentVolumeClaim:
            claimName: ingestion-volume-dags
        - name: ingestion-volume-tmp
          persistentVolumeClaim:
            claimName: ingestion-volume-tmp
