apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yaml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: openmetadata-server
  name: openmetadata-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: openmetadata-server
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file docker-compose.yaml convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: openmetadata-server
    spec:
      containers:
        - env:
            - name: AIRFLOW_PASSWORD
              value: admin
            - name: AIRFLOW_TIMEOUT
              value: "10"
            - name: AIRFLOW_TRUST_STORE_PASSWORD
              value: '""'
            - name: AIRFLOW_TRUST_STORE_PATH
              value: '""'
            - name: AIRFLOW_USERNAME
              value: admin
            - name: AUTHENTICATION_AUTHORITY
              value: https://accounts.google.com
            - name: AUTHENTICATION_CALLBACK_URL
              value: '""'
            - name: AUTHENTICATION_CLIENT_ID
              value: '""'
            - name: AUTHENTICATION_CLIENT_TYPE
              value: public
            - name: AUTHENTICATION_ENABLE_SELF_SIGNUP
              value: "true"
            - name: AUTHENTICATION_JWT_PRINCIPAL_CLAIMS
              value: '[email,preferred_username,sub]'
            - name: AUTHENTICATION_JWT_PRINCIPAL_CLAIMS_MAPPING
              value: '[]'
            - name: AUTHENTICATION_PROVIDER
              value: basic
            - name: AUTHENTICATION_PUBLIC_KEYS
              value: '[http://localhost:8585/api/v1/system/config/jwks]'
            - name: AUTHENTICATION_RESPONSE_TYPE
              value: id_token
            - name: AUTHORIZER_ADMIN_PRINCIPALS
              value: '[admin]'
            - name: AUTHORIZER_ALLOWED_REGISTRATION_DOMAIN
              value: '["all"]'
            - name: AUTHORIZER_CLASS_NAME
              value: org.openmetadata.service.security.DefaultAuthorizer
            - name: AUTHORIZER_ENABLE_SECURE_SOCKET
              value: "false"
            - name: AUTHORIZER_ENABLE_SMTP
              value: "false"
            - name: AUTHORIZER_ENFORCE_PRINCIPAL_DOMAIN
              value: "false"
            - name: AUTHORIZER_INGESTION_PRINCIPALS
              value: '[ingestion-bot]'
            - name: AUTHORIZER_PRINCIPAL_DOMAIN
              value: '"open-metadata.org"'
            - name: AUTHORIZER_REQUEST_FILTER
              value: org.openmetadata.service.security.JwtFilter
            - name: CUSTOM_OIDC_AUTHENTICATION_PROVIDER_NAME
              value: '""'
            - name: DB_DRIVER_CLASS
              value: com.mysql.cj.jdbc.Driver
            - name: DB_HOST
              value: mysql
            - name: DB_PARAMS
              value: allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
            - name: DB_PORT
              value: "3306"
            - name: DB_SCHEME
              value: mysql
            - name: DB_USER
              value: openmetadata_user
            - name: DB_USER_PASSWORD
              value: openmetadata_password
            - name: ELASTICSEARCH_BATCH_SIZE
              value: "100"
            - name: ELASTICSEARCH_CONNECTION_TIMEOUT_SECS
              value: "5"
            - name: ELASTICSEARCH_HOST
              value: ' elasticsearch'
            - name: ELASTICSEARCH_INDEX_MAPPING_LANG
              value: EN
            - name: ELASTICSEARCH_KEEP_ALIVE_TIMEOUT_SECS
              value: "600"
            - name: ELASTICSEARCH_PASSWORD
              value: '""'
            - name: ELASTICSEARCH_PAYLOAD_BYTES_SIZE
              value: "10485760"
            - name: ELASTICSEARCH_PORT
              value: "9200"
            - name: ELASTICSEARCH_SCHEME
              value: http
            - name: ELASTICSEARCH_SOCKET_TIMEOUT_SECS
              value: "60"
            - name: ELASTICSEARCH_TRUST_STORE_PASSWORD
              value: '""'
            - name: ELASTICSEARCH_TRUST_STORE_PATH
              value: '""'
            - name: ELASTICSEARCH_USER
              value: '""'
            - name: EVENT_MONITOR
              value: prometheus
            - name: EVENT_MONITOR_BATCH_SIZE
              value: "10"
            - name: EVENT_MONITOR_LATENCY
              value: '[]'
            - name: EVENT_MONITOR_PATH_PATTERN
              value: '["/api/v1/tables/*", "/api/v1/health-check"]'
            - name: FERNET_KEY
              value: jJ/9sz0g0OHxsfxOoSfdFdmk3ysNmPRnH3TUAbz3IHA=
            - name: JWT_ISSUER
              value: '"open-metadata.org"'
            - name: JWT_KEY_ID
              value: '"Gb389a-9f76-gdjs-a92j-0242bk94356"'
            - name: LOG_LEVEL
              value: INFO
            - name: MASK_PASSWORDS_API
              value: "false"
            - name: OIDC_CALLBACK
              value: '"http://localhost:8585/callback"'
            - name: OIDC_CLIENT_AUTH_METHOD
              value: '"client_secret_post"'
            - name: OIDC_CLIENT_ID
              value: '""'
            - name: OIDC_CLIENT_SECRET
              value: '""'
            - name: OIDC_CUSTOM_PARAMS
              value: '{}'
            - name: OIDC_DISABLE_PKCE
              value: "true"
            - name: OIDC_DISCOVERY_URI
              value: '""'
            - name: OIDC_MAX_CLOCK_SKEW
              value: '""'
            - name: OIDC_PREFERRED_JWS
              value: '"RS256"'
            - name: OIDC_RESPONSE_TYPE
              value: '"code"'
            - name: OIDC_SCOPE
              value: '"openid email profile"'
            - name: OIDC_SERVER_URL
              value: '"http://localhost:8585"'
            - name: OIDC_TENANT
              value: '""'
            - name: OIDC_TYPE
              value: '""'
            - name: OIDC_USE_NONCE
              value: "true"
            - name: OM_DATABASE
              value: openmetadata_db
            - name: OM_EMAIL_ENTITY
              value: '"OpenMetadata"'
            - name: OM_SM_ACCESS_KEY
              value: '""'
            - name: OM_SM_ACCESS_KEY_ID
              value: '""'
            - name: OM_SM_REGION
              value: '""'
            - name: OM_SUPPORT_URL
              value: '"https://slack.open-metadata.org"'
            - name: OPENMETADATA_CLUSTER_NAME
              value: openmetadata
            - name: OPENMETADATA_HEAP_OPTS
              value: -Xmx1G -Xms1G
            - name: OPENMETADATA_SERVER_URL
              value: '""'
            - name: OPENMETADATA_SMTP_SENDER_MAIL
              value: '""'
            - name: PIPELINE_SERVICE_CLIENT_CLASS_NAME
              value: '"org.openmetadata.service.clients.pipeline.airflow.AirflowRESTClient"'
            - name: PIPELINE_SERVICE_CLIENT_ENABLED
              value: "true"
            - name: PIPELINE_SERVICE_CLIENT_ENDPOINT
              value: http://ingestion:8080
            - name: PIPELINE_SERVICE_CLIENT_HEALTH_CHECK_INTERVAL
              value: "300"
            - name: PIPELINE_SERVICE_CLIENT_HOST_IP
              value: '""'
            - name: PIPELINE_SERVICE_CLIENT_SECRETS_MANAGER_LOADER
              value: '"noop"'
            - name: PIPELINE_SERVICE_CLIENT_SSL_CERT_PATH
              value: '""'
            - name: PIPELINE_SERVICE_CLIENT_VERIFY_SSL
              value: '"no-ssl"'
            - name: PIPELINE_SERVICE_IP_INFO_ENABLED
              value: "false"
            - name: RSA_PRIVATE_KEY_FILE_PATH
              value: '"./conf/private_key.der"'
            - name: RSA_PUBLIC_KEY_FILE_PATH
              value: '"./conf/public_key.der"'
            - name: SEARCH_TYPE
              value: ' "elasticsearch"'
            - name: SECRET_MANAGER
              value: db
            - name: SERVER_ADMIN_PORT
              value: "8586"
            - name: SERVER_HOST_API_URL
              value: http://openmetadata-server:8585/api
            - name: SERVER_PORT
              value: "8585"
            - name: SMTP_SERVER_ENDPOINT
              value: '""'
            - name: SMTP_SERVER_PORT
              value: '""'
            - name: SMTP_SERVER_PWD
              value: '""'
            - name: SMTP_SERVER_STRATEGY
              value: '"SMTP_TLS"'
            - name: SMTP_SERVER_USERNAME
              value: '""'
            - name: WEB_CONF_CACHE_CONTROL
              value: '""'
            - name: WEB_CONF_CONTENT_TYPE_OPTIONS_ENABLED
              value: "false"
            - name: WEB_CONF_FRAME_OPTION
              value: '"SAMEORIGIN"'
            - name: WEB_CONF_FRAME_OPTION_ENABLED
              value: "false"
            - name: WEB_CONF_FRAME_ORIGIN
              value: '""'
            - name: WEB_CONF_HSTS_ENABLED
              value: "false"
            - name: WEB_CONF_HSTS_INCLUDE_SUBDOMAINS
              value: '"true"'
            - name: WEB_CONF_HSTS_MAX_AGE
              value: '"365 days"'
            - name: WEB_CONF_HSTS_PRELOAD
              value: '"true"'
            - name: WEB_CONF_PRAGMA
              value: '""'
            - name: WEB_CONF_URI_PATH
              value: '"/api"'
            - name: WEB_CONF_XSS_CSP_ENABLED
              value: "false"
            - name: WEB_CONF_XSS_CSP_POLICY
              value: '"default-src ''self''"'
            - name: WEB_CONF_XSS_CSP_REPORT_ONLY_POLICY
              value: '""'
            - name: WEB_CONF_XSS_PROTECTION_BLOCK
              value: "true"
            - name: WEB_CONF_XSS_PROTECTION_ENABLED
              value: "false"
            - name: WEB_CONF_XSS_PROTECTION_ON
              value: "true"
          image: docker.getcollate.io/openmetadata/server:1.5.6
          livenessProbe:
            exec:
              command:
                - wget
                - -q
                - --spider
                - http://localhost:8586/healthcheck
          name: openmetadata-server
          ports:
            - containerPort: 8585
              protocol: TCP
            - containerPort: 8586
              protocol: TCP
      restartPolicy: Always
